#!/bin/cat

Hi.
This is an "Is-ness" .can: File
    *) The *.can files can update your system, such that, it{the_system) would result in ma{+s}y *.is and *.has files
    ?) This is freeform text! It i_s depending on: BASH+PYTHON+HTML+JAVASCRIPT+ANd a bit of C++ `Stop!;``Stop-ped;`lol;
    -)) ??
    key)) value
    *) index.none
                       -> `Protocol:Glaglo!?no==Tru-th;yes==False-hood;
Enjoy!
\n
\w\n
.en-joyed??
